[tool.poetry]
name = "ping-back"
version = "1.0.0"
description = "ping-back API hosted by Divide Projects!"
authors = ["Divanshu Chauhan <techdroidroot@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.78.0"
gunicorn = "^20.1.0"
uvicorn = "^0.18.1"
requests = "^2.27.1"
prettyconf = "^2.2.1"
validators = "^0.20.0"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pre-commit = "^2.19.0"
pyclean = "^2.2.0"
pylint = "^2.14.1"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
