[tool.poetry]
name = "ping-back"
version = "1.0.0"
description = "ping-back API hosted by Divide Projects!"
authors = ["Divanshu Chauhan <techdroidroot@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.89.1"
gunicorn = "^20.1.0"
uvicorn = "^0.20.0"
requests = "^2.28.2"
prettyconf = "^2.2.1"
validators = "^0.20.0"

[tool.poetry.dev-dependencies]
black = "^22.12.0"
pre-commit = "^2.21.0"
pyclean = "^2.6.0"
pylint = "^2.15.10"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
