[tool.poetry]
name = "tools"
version = "1.0.0"
description = "Tools hosted by divideprojects!"
authors = ["Divanshu Chauhan <techdroidroot@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fastapi = "^0.78.0"
gunicorn = "^20.1.0"
uvicorn = "^0.17.6"
pytube = "^12.1.0"
dnspython = "^2.2.1"
pypers = "^1.2.1"
requests = "^2.27.1"
prettyconf = "^2.2.1"
validators = "^0.20.0"

[tool.poetry.dev-dependencies]
black = "^22.3"
pre-commit = "^2.19.0"
pyclean = "^2.2.0"
pylint = "^2.14.1"
isort = "^5.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
